---
- name: Install Node.js
  hosts: integ
  become: yes
  vars:
    docker_image_name: "agaonka2/integ-20231203183247"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Upgrade packages (security updates only)
      apt:
        upgrade: "safe"
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'

    - name: Create directory if it doesn't exist
      file:
        path: /etc/docker
        state: directory
        mode: '0755'
    
    - name: Create Docker Daemon configuration file
      copy:
        content: |
          {
            "metrics-addr": "0.0.0.0:9323",
            "experimental": true
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

    - name: Restart docker
      shell:
        "sudo systemctl restart docker"

    - name: Expose port 9323 with iptables
      shell: 
        "sudo iptables -I INPUT -p tcp -m tcp --dport 9323 -j ACCEPT"

    - name: Install Python3 pip
      apt:
        name: python3-pip
        state: present
      become: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Docker Python library
      pip:
        name: docker
      become: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        source: pull
        state: present
      register: docker_image_result

    - name: Run Docker container
      docker_container:
        name: my_container
        image: "{{ docker_image_name }}"
        state: started
        ports:
          - "3000:3000"
      register: docker_container_result