---
- name: Install and configure Grafana and Prometheus
  hosts: monitoring_server
  become: yes

  tasks:
    - name: Install required package
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - adduser
        - libfontconfig1
        - musl

    - name: Download Grafana package
      get_url:
        url: "https://dl.grafana.com/oss/release/grafana_10.0.0_amd64.deb"
        dest: "/tmp/grafana_10.0.0_amd64.deb"

    - name: Install Grafana package
      apt:
        deb: "/tmp/grafana_10.0.0_amd64.deb"
      args:
        update_cache: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started

    - name: Expose port 3000 with iptables
      shell: 
        "sudo iptables -I INPUT -p tcp -m tcp --dport 3000 -j ACCEPT"  

    - name: Stop unattended upgrades
      shell: 
        "sudo systemctl stop unattended-upgrades" 

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no
      with_items:
        - prometheus

    - name: Copy custom Prometheus configuration
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify:
        - Restart Prometheus

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Expose port 9090 with iptables
      shell: 
        "sudo iptables -I INPUT -p tcp -m tcp --dport 9090 -j ACCEPT"    

  handlers:
    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted
