# This workflow generates a code coverage report
defaults:
  run:
    working-directory: coffee-project

name: Generating Code Coverage Report

on: [push, pull_request]

env:
  NODE_VERSION: 14

jobs:
  build:
    name: Generate report 
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Install dependencies
        run: npm install chai mocha-lcov-reporter nyc --save-dev

      - name: Run tests
        run: npm run covtest

      - name: Run coverage
        run: npm run coverage

      - name: Check code coverage
        run: |
          COVERAGE_PERCENTAGE=$(npx nyc report --reporter=text-summary | grep -oP 'Statements\s+:\s+\K[0-9]+(?=%)')

          if [ "$COVERAGE_PERCENTAGE" -lt 90 ]; then
            echo "[FAIL] Code Coverage is less than 90%. Current coverage is ($COVERAGE_PERCENTAGE)%"
            exit 1
          else
            echo "[PASS] Code Coverage is ($COVERAGE_PERCENTAGE)%. It passes the Code Coverage Criteria of being over 90%"
          fi
