name: Lint

on:
  push:
    branches:
      - dev
      
env:
  NODE_VERSION: 14

jobs: 
  linting:
    name: Linting 
    runs-on: self-hosted 
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2
        
      - name: Switch Directory
        run: cd coffee-project

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
