name: Deploy on PROD

on:
  push:
    branches:
      - PROD

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy deploy.yml and hosts.yml to Desktop
      run: |
        mkdir -p $HOME/deploy
        cp deploy.yml $HOME/deploy
        cp hosts.yml $HOME/deploy

    - name: Display copied files
      run: ls $HOME/deploy

    - name: Run Ansible playbook
      run: ansible-playbook -i $HOME/deploy/hosts.yml $HOME/deploy/deploy.yml