# This workflow runs the unit test cases in the /coffee-project/test directory
defaults:
  run:
    working-directory: coffee-project

name: Running Unit Test Cases

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened]

env:
  NODE_VERSION: 14

jobs:
  build:
    name: Run Test Cases
    runs-on: self-hosted
    steps:
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Install Dependencies
        run: npm install mocha chai supertest --save-dev

      - name: Run unit tests
        run: npm test
